export const authConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGUOT: 'USERS_LOGOUT',

    AUTH_LOAD_USER_REQUEST: 'AUTH_LOAD_USER_REQUEST',
    AUTH_LOAD_USER_SUCCESS: 'AUTH_LOAD_USER_SUCCESS',
    AUTH_LOAD_USER_FAILURE: 'AUTH_LOAD_USER_FAILURE',
};