export const commentConstants = {

    COMMENT_LOAD_SUCCESS: 'COMMENT_LOAD_SUCCESS',
    COMMENT_LOAD_FAILURE: 'COMMENT_LOAD_FAILURE',

    USERINFO_LOAD_SUCCESS: 'USERINFO_LOAD_SUCCESS',
    USERINFO_LOAD_FAILURE: 'USERINFO_LOAD_FAILURE'

};