export const eventConstant = {
    CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',
    CREATE_FAILURE: 'EVENT_CREATE_FAILURE',

    FETCH_LIST_OF_FRIENDS_EVENTS_SUCCESS: 'FETCH_LIST_OF_FRIENDS_EVENTS_SUCCESS',
    FETCH_LIST_OF_FRIENDS_EVENTS_FAILURE: 'FETCH_LIST_OF_FRIENDS_EVENTS_FAILURE',

    EVENT_JOIN_SUCESS: 'EVENT_JOIN_SUCESS',
    EVENT_JOIN_FAILURE: 'EVENT_JOIN_FAILURE',

    EVENT_DELETE_SUCCESS: 'EVENT_DELETE_SUCCESS',
    EVENT_DELETE_FAILURE: 'EVENT_DELETE_FAILURE',

    EVENT_INVITE_FRIEND_SUCCESS: 'EVENT_INVITE_FRIEND_SUCCESS',
    EVENT_INVITE_FRIEND_FAILURE: 'EVENT_INVITE_FRIEND_FAILURE',

    EVENT_FETCH_PHOTO_SUCCESS: 'EVENT_FETCH_PHOTO_SUCCESS',
    EVENT_FETCH_PHOTO_FAILURE: 'EVENT_FETCH_PHOTO_FAILURE',
};