export const eventConstant = {
    CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',
    CREATE_FAILURE: 'EVENT_CREATE_FAILURE',

    FETCH_LIST_OF_EVENTS_SUCCESS: 'FETCH_LIST_OF_EVENTS_SUCCESS',
    FETCH_LIST_OF_EVENTS_FAILURE: 'FETCH_LIST_OF_EVENTS_FAILURE',

    DELETE_EVENT: 'DELETE_EVENT'
};