export const eventConstant = {
    CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',
    CREATE_FAILURE: 'CREATE_FAILURE',

    FETCH_LIST_OF_POSTS_SUCCESS: 'FETCH_LIST_OF_POSTS_SUCCESS',
    FETCH_LIST_OF_POSTS_FAILURE: 'FETCH_LIST_OF_POSTS_FAILURE',

    DELETE_POST: 'DELETE_POST'
};