export const postConstants = {
    POST_LOAD_REQUEST: 'POST_LOAD_REQUEST',
    POST_LOAD_SUCCESS: 'POST_LOAD_SUCCESS',
    POST_LOAD_FAILURE: 'POST_LOAD_FAILURE',

    COMMENT_LOAD_REQUEST: 'COMMENT_LOAD_REQUEST',
    COMMENT_LOAD_SUCCESS: 'COMMENT_LOAD_SUCCESS',
    COMMENT_LOAD_FAILURE: 'COMMENT_LOAD_FAILURE'

};