export const postConstants = {
    POST_LOAD_REQUEST: 'POST_LOAD_REQUEST',
    POST_LOAD_SUCCESS: 'POST_LOAD_SUCCESS',
    POST_LOAD_FAILURE: 'POST_LOAD_FAILURE',

    POST_CREATE_REQUEST: 'POST_CREATE_REQUEST',
    POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
    POST_CREATE_FAILURE: 'POST_CREATE_FAILURE',



};