export const userConstants = {

    USER_PROFILE_LOAD_SUCCESS: 'USER_PROFILE_LOAD_SUCCESS',
    USER_PROFILE_LOAD_FAILURE: 'USER_PROFILE_LOAD_FAILURE',

    USER_FRIENDS_LOAD_SUCCESS: 'USER_FRIENDS_LOAD_SUCCESS',
    USER_FRIENDS_LOAD_FAILURE: 'USER_FRIENDS_LOAD_FAILURE',

    FETCH_USER_EVENTS_SUCCESS: 'FETCH_USER_EVENTS_SUCCESS',
    FETCH_USER_EVENTS_FAILURE: 'FETCH_USER_EVENTS_FAILURE',

    ADD_FRIEND_SUCCESS: 'ADD_FRIEND_SUCCESS',
    ADD_FRIEND_FAILURE: 'ADD_FRIEND_FAILURE',

    DELETE_FRIEND_SUCCESS: 'DELETE_FRIEND_SUCCESS',
    DELETE_FRIEND_FAILURE: 'DELETE_FRIEND_FAILURE',

    DELETE_INVITE_SUCCESS: 'DELETE_INVITE_SUCCESS',
    DELETE_INVITE_FAILURE: 'DELETE_INVITE_FAILURE',

    ACCEPT_INVITE_SUCCESS: 'ACCEPT_INVITE_SUCCESS',
    ACCEPT_INVITE_FAILURE: 'ACCEPT_INVITE_FAILURE',

    FETCH_INVITED_EVENTS_SUCCESS: 'FETCH_INVITED_EVENTS_SUCCESS',
    FETCH_INVITED_EVENTS_FAILURE: 'FETCH_INVITED_EVENTS_FAILURE',
};