export const userConstants = {

    USER_PROFILE_LOAD_SUCCESS: 'USER_PROFILE_LOAD_SUCCESS',
    USER_PROFILE_LOAD_FAILURE: 'USER_PROFILE_LOAD_FAILURE',

    USER_PROFILE_UPDATE_SECCESS: 'USER_PROFILE_UPDATE_SECCESS',
    USER_PROFILE_UPDATE_FAILURE: 'USER_PROFILE_UPDATE_FAILURE',

    USER_FRIENDS_LOAD_SUCCESS: 'USER_FRIENDS_LOAD_SUCCESS',
    USER_FRIENDS_LOAD_FAILURE: 'USER_FRIENDS_LOAD_FAILURE',
};